### ISSUE TITLE
Tensorflow issue

### ISSUE THREAD

**Issue by LLL184** [qqqwda/pokemeow-captcha-api#13]
D:\pokemeow-captcha-api-develop>py apiv2.py
Traceback (most recent call last):
  File "D:\pokemeow-captcha-api-develop\apiv2.py", line 4, in <module>
    import tensorflow as tf
  File "D:\Python\lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from ._api.v2 import __internal__
  File "D:\Python\lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 11, in <module>
    from . import distribute
  File "D:\Python\lib\site-packages\tensorflow\_api\v2\__internal__\distribute\__init__.py", line 8, in <module>
    from . import combinations
  File "D:\Python\lib\site-packages\tensorflow\_api\v2\__internal__\distribute\combinations\__init__.py", line 23, in <module>
    from tensorflow.python.distribute.strategy_combinations import multi_worker_mirrored_2x1_gpu_noshare
ImportError: cannot import name 'multi_worker_mirrored_2x1_gpu_noshare' from 'tensorflow.python.distribute.strategy_combinations' (D:\Python\lib\site-packages\tensorflow\python\distribute\strategy_combinations.py)

**Comment by LLL184** [comment]
The error at first was cublas64_11.dll not found but after I reinstalled cuda and cudnn it became like this pls help me

**Comment by qqqwda** [comment]
can you provide the python version you are using?

**Comment by LLL184** [comment]
python 3.10 only

**Comment by qqqwda** [comment]
Im not sure why it's trying to use the GPU instead of CPU, did you change anything in code?

**Comment by LLL184** [comment]
No, I just downloaded and used it

**Comment by qqqwda** [comment]
did you tried uninstalling tensorflow:
`pip uninstall tensorflow`
and then
`pip install -r requirements.txt`

**Comment by LLL184** [comment]
![image](https://github.com/user-attachments/assets/5b554476-4456-4cb5-8387-8a216f179d4a)

**Comment by qqqwda** [comment]
can you test the captcha solver? I think you sre good to go 🙂

**Comment by LLL184** [comment]
I didn't expect it but thank you

**Comment by LLL184** [comment]
I didn't expect that but thank you
